apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: test-istio-v3
spec:
  config:
    auth:
      disable_login_form: "false"
      disable_signout_menu: "false"
    log:
      level: info
      mode: console
    server:
      root_url: '%(protocol)s://%(domain)s/'
  route:
    spec:
      tls:
        termination: edge