apiVersion: v1
kind: Secret
metadata:
  name: tempo-storage-secret
  namespace: istio-tempo
type: Opaque
stringData:
  endpoint: http://minio.minio.svc:9000
  access_key_id: PVYxWNd3tZAIvAk27i4k
  access_key_secret: jXrjxziQRPPVjbegSTDPDenTMb30WiOEGBMtE8Pu
  bucket: tempo-smcp
---
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: istio-tempostack
  namespace: istio-tempo
spec:
  tenants:
    mode: openshift
    authentication:
      - tenantName: dev
        tenantId: dev
      - tenantName: prod
        tenantId: prod
  storage:
    secret:
      name: tempo-storage-secret
      type: s3
    trace:
      backend: s3
  replicationFactor: 1
  retention:
    global:
      traces: 48h
  template:
    gateway:
      enabled: true
    queryFrontend:
      jaegerQuery:
        enabled: true  
  limits:
    global:
      ingestion:
        rate: 10000
        burstSize: 20000
      query:
        timeout: 30s
  observability:
    grafana:
      enabled: true