apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: _CONTROL_PLANE_
spec:
  namespace: _CONTROL_PLANE_
  values:
    pilot:
      autoscaleMin: 1
      autoscaleMax: 5
      cpu:
        targetAverageUtilization: 80 
      memory:
        targetAverageUtilization: 80 
    meshConfig:
      enableTracing: true
      extensionProviders:
      - name: otel
        opentelemetry:
          port: 4317
          service: otel-collector._CONTROL_PLANE_.svc.cluster.local 
      discoverySelectors:
        - matchLabels:
            istio.io/rev: _CONTROL_PLANE_

