kind: OpenTelemetryCollector
apiVersion: opentelemetry.io/v1beta1
metadata:
  name: otel
spec:
  replicas: 2
  # Para autoscaler habria que definir requests
  # autoscaler:
  #   minReplicas: 1
  #   maxReplicas: 3
  #   targetCPUUtilization: 50
  #   targetMemoryUtilization: 60
  observability:
    metrics:
      enableMetrics: true
  deploymentUpdateStrategy: {}
  config:
    exporters:
      otlp:
        endpoint: 'tempo-istio-tempostack-gateway._TEMPO_NAMESPACE_.svc:8090'
        tls:
          insecure: false
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: "_TENANT_"
    extensions:
      bearertokenauth:
        filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"           
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: '0.0.0.0:4317'
          http: {}
    service:
      extensions: [bearertokenauth]
      pipelines:
        traces:
          exporters:
            - otlp
          receivers:
            - otlp