apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: monitoring-stack
spec:
  alertmanagerConfig:
    disabled: true
  logLevel: debug
  retention: 3d
  namespaceSelector:
    matchLabels:
      istio.io/rev: _CONTROL_PLANE_
  resourceSelector: {}
