apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: istiod-monitor
  labels:
    istio.io/rev: test-smcp-v2
spec:
  selector:
    matchLabels:
      istio: pilot
  endpoints:
  - port: http-monitoring
    interval: 30s
    scheme: http