apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  labels:
    mesh-app: test-smcp-v2
  name: istiod-monitor
spec:
  selector:
    matchLabels:
      istio: pilot
  endpoints:
  - port: http-monitoring
    interval: 30s
    scheme: http