apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: istiod-monitor
  labels:
    monitoring: "monitoring-stack"
spec:
  selector:
    matchLabels:
      istio: pilot
  endpoints:
  - port: http-monitoring
    interval: 30s
    scheme: http