apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: ossm-controlplane-v2
  namespace: test-smcp-v2
spec:
  tracing:
    type: Jaeger
    sampling: 1000
  gateways:
    ingress:
      runtime:
        deployment:
          replicas: 2
          autoScaling:
            enabled: false
    egress:
      enabled: false
    openshiftRoute:
      enabled: false
  policy:
    type: Istiod
  telemetry:
    type: Istiod

  addons:
    grafana:
      enabled: true
      install:
        persistence:
          enabled: false
        service:
          ingress:
            enabled: true
    jaeger:
      name: jaeger
      install:
        ingress:
          enabled: true
        storage:
          type: Elasticsearch # or Memory
          memory:
            maxTraces: 100000
          elasticsearch:
            nodeCount: 1
            storage:
              size: 5Gi
              storageClassName: nfs-csi
            redundancyPolicy: ZeroRedundancy
            indexCleaner:
              enabled: true
              numberOfDays: 7
              schedule: "55 23 * * *"
    kiali:
      name: kiali
      enabled: true
      install: # install kiali CR if not present
        dashboard:
          viewOnly: true
          enableGrafana: true
          enableTracing: true
          enablePrometheus: true
        service:
          ingress:
            enabled: true
    prometheus:
      enabled: true
      install:
        service:
          ingress:
            enabled: true
  runtime:
    defaults:
      deployment:
        replicas: 1
        autoScaling:
          enabled: false
    components:
      pilot: # istiod
        deployment:
          replicas: 1
          autoScaling:
            enabled: false
      grafana:
        deployment:
          replicas: 1
          autoScaling:
            enabled: false
      kiali:
        deployment:
          replicas: 1
          autoScaling:
            enabled: false
      prometheus:
        deployment:
          replicas: 1
          autoScaling:
            enabled: false
