apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: _CONTROL_PLANE_
spec:
  namespace: _CONTROL_PLANE_
  values:
    pilot:
      replicaCount: 2
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 500m
          memory: 2Gi
    proxy:
      resources:
        requests:
          cpu: 125m
          memory: 150Mi
        limits:
          cpu: 125m
          memory: 150Mi
    meshConfig:
      enableTracing: true
      extensionProviders:
      - name: otel
        opentelemetry:
          port: 4317
          service: otel-collector._CONTROL_PLANE_.svc.cluster.local 
      discoverySelectors:
        - matchLabels:
            istio.io/rev: _CONTROL_PLANE_

