apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-_CONTROL_PLANE_-traces-read-_TENANT_
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-_TEMPO_NAMESPACE_-traces-read-_TENANT_
subjects:
- kind: ServiceAccount
  name: kiali-service-account
  namespace: _CONTROL_PLANE_
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-_CONTROL_PLANE_-traces-write-_TENANT_
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-_TEMPO_NAMESPACE_-traces-write-_TENANT_
subjects:
- kind: ServiceAccount
  name: otel-collector
  namespace: _CONTROL_PLANE_