apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-_TEMPO_NAMESPACE_-traces-read-_TENANT_
rules:
- apiGroups:
  - tempo.grafana.com
  resources:
  - _TENANT_
  resourceNames:
  - traces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-_TEMPO_NAMESPACE_-traces-write-_TENANT_
rules:
- apiGroups:
  - tempo.grafana.com
  resources:
  - _TENANT_
  resourceNames:
  - traces
  verbs:
  - get
  - list
  - watch
  - create

